export default {
	ADD_CLASSROOM: 'ADD_CLASSROOM',
	ADD_DOCUMENT: 'ADD_DOCUMENT',
	ADD_NEW_MATERIAL: 'ADD_NEW_MATERIAL',
	EDIT_CLASSROOM: 'EDIT_CLASSROOM',
	REMOVE_CLASSROOM: 'REMOVE_CLASSROOM',
	SESSION_DESTROY: 'SESSION_DESTROY',
	SET_CLASSROOMS: 'SET_CLASSROOMS',
	SET_DOCUMENTS: 'SET_DOCUMENTS',
	SET_MATERIALS: 'SET_MATERIALS',
	SET_SESSION: 'SET_SESSION',
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
}